/**
 * Sylvia's full à la carte food menu, auto-generated from the cloned /food-menu page
 * (scripts/regenerate: scripts/generate-menu-data.py). Every item mirrors the live site
 * — name, price, description, category, and the real menu photo where one exists.
 * Plain data (no server-only imports) — safe on client + server.
 */

export type MenuItem = {
  name: string;
  description: string;
  /** Base price in USD; 0 when the price isn't a single number (see priceNote). */
  price: number;
  priceNote?: string;
  category: string;
  tags: string[];
  /** Stable id for the /menu deep-link (?item=slug) and card keys. */
  slug: string;
  /** Real menu photo (Sylvia's CDN), or undefined when the live menu has none. */
  image?: string;
};

export const MENU: MenuItem[] = [
  {
    name: "Fried Chicken Wings",
    description: "Mix of flats and drums.",
    price: 16,
    category: "Appetizers",
    tags: ["chicken", "fried"],
    slug: "fried-chicken-wings",
    image: "https://static.spotapps.co/spots/4d/f4c90dbb1542e79d67470f2a730d94/medium",
  },
  {
    name: "Catfish Fingers",
    description: "w/House-Made Tartar Sauce",
    price: 19,
    category: "Appetizers",
    tags: ["seafood"],
    slug: "catfish-fingers",
    image: "https://static.spotapps.co/spots/ed/278da7be0f4968bfb95e1c10ded8c3/medium",
  },
  {
    name: "Spicy Fish Fritters",
    description: "w/House-Made Tartar Sauce",
    price: 16,
    category: "Appetizers",
    tags: ["seafood", "spicy"],
    slug: "spicy-fish-fritters",
  },
  {
    name: "Chicken Livers",
    description: "Sauteed with onions & peppers with Sylvia\u2019s brown gravy.",
    price: 13,
    category: "Appetizers",
    tags: ["chicken"],
    slug: "chicken-livers",
    image: "https://static.spotapps.co/spots/d9/d73aeabdbc48889fd312a0e7f5ca85/medium",
  },
  {
    name: "Sylvia\u2019s Down Home Fried Chicken",
    description: "",
    price: 25,
    category: "Chicken Selections",
    tags: ["chicken", "fried"],
    slug: "sylvias-down-home-fried-chicken",
    image: "https://static.spotapps.co/spots/11/839a54f6324b5d9e7fe4c46592ad11/medium",
  },
  {
    name: "Sylvia\u2019s Smothered Chicken",
    description: "Lightly fried chicken slow-cooked in Sylvia\u2019s brown gravy.",
    price: 25,
    category: "Chicken Selections",
    tags: ["chicken", "fried"],
    slug: "sylvias-smothered-chicken",
  },
  {
    name: "Oven Baked Half Chicken",
    description: "Seasoned to perfection with fresh herb.",
    price: 26,
    category: "Chicken Selections",
    tags: ["chicken", "grilled"],
    slug: "oven-baked-half-chicken",
    image: "https://static.spotapps.co/spots/44/71582d9128443f86ec3c3dedc3646d/medium",
  },
  {
    name: "Bar-B-Que Ribs",
    description: "Sylvia's World Famous Talked about BAR-B-QUE pork ribs with Sylvia\u2019s original sassy sauce.",
    price: 29,
    category: "Pork Selections",
    tags: ["pork", "grilled"],
    slug: "bar-b-que-ribs",
    image: "https://static.spotapps.co/spots/be/b2a5498def484c9ea533085546004a/medium",
  },
  {
    name: "Pork Chops",
    description: "One Pork Chop $25.00 | Two Pork Chops $32.00 Golden Fried, (GF) Grilled or Smothered",
    price: 0,
    category: "Pork Selections",
    tags: ["pork", "fried", "grilled"],
    slug: "pork-chops",
    image: "https://static.spotapps.co/spots/f2/334de4b0274b72bf5c5aead6dacf05/medium",
  },
  {
    name: "Tasty Carolina Style Fried or Grilled Catfish",
    description: "",
    price: 30,
    category: "Seafood Selections",
    tags: ["seafood", "fried", "grilled"],
    slug: "tasty-carolina-style-fried-or-grilled-catfish",
    image: "https://static.spotapps.co/spots/9f/94bab133e94bbd8a3df181e5a599d5/medium",
  },
  {
    name: "Grandma Julia\u2019s Cornmeal Fried Whiting",
    description: "",
    price: 25,
    category: "Seafood Selections",
    tags: ["seafood", "fried"],
    slug: "grandma-julias-cornmeal-fried-whiting",
  },
  {
    name: "Grilled Atlantic Bar-B-Que Salmon",
    description: "",
    price: 32,
    category: "Seafood Selections",
    tags: ["seafood", "grilled"],
    slug: "grilled-atlantic-bar-b-que-salmon",
    image: "https://static.spotapps.co/spots/72/b6654141bc42fea3041caff421545f/medium",
  },
  {
    name: "Soulful Caesar Salad - Kale and Mixed Greens (V)",
    description: "Add: Grilled Chicken +$10 Grilled Salmon +$16",
    price: 15,
    category: "Salads & More",
    tags: ["chicken", "seafood", "vegetarian", "grilled"],
    slug: "soulful-caesar-salad-kale-and-mixed-greens",
  },
  {
    name: "Watermelon Salad",
    description: "Arugula w/ Feta Cheese and Balsamic Vinaigrette",
    price: 16,
    category: "Salads & More",
    tags: ["vegetarian"],
    slug: "watermelon-salad",
    image: "https://static.spotapps.co/spots/67/a3052d50b8409596346427060f4c33/medium",
  },
  {
    name: "Veggie Platter (V)",
    description: "Choose 4 Sides - Limited to one of each choice",
    price: 28,
    category: "Salads & More",
    tags: ["vegetarian"],
    slug: "veggie-platter",
    image: "https://static.spotapps.co/spots/16/3a16f61ee64801b6bb864dc2400c13/medium",
  },
  {
    name: "Sylvia\u2019s Chicken Sandwich",
    description: "With French Fries Fried, grilled or BBQ chicken breast on a toasted brioche bun with mayo and house pickles .",
    price: 20,
    category: "Sandwiches & Burgers",
    tags: ["chicken", "beef", "fried", "grilled"],
    slug: "sylvias-chicken-sandwich",
  },
  {
    name: "Sylvia\u2019s Sassy Angus Beef Burger",
    description: "With French Fries Sylvia\u2019s signature beef burger on a brioche bun with lettuce, tomato, sliced onion, and house pickles, cooked medium well unless otherwise specified.",
    price: 23,
    category: "Sandwiches & Burgers",
    tags: ["beef"],
    slug: "sylvias-sassy-angus-beef-burger",
  },
  {
    name: "Waffle (V)",
    description: "",
    price: 14,
    category: "Waffle Selections",
    tags: ["vegetarian", "sweet"],
    slug: "waffle",
  },
  {
    name: "Waffle with Harlem Style Fried Chicken",
    description: "",
    price: 24,
    category: "Waffle Selections",
    tags: ["chicken", "fried", "sweet"],
    slug: "waffle-with-harlem-style-fried-chicken",
    image: "https://static.spotapps.co/spots/35/ad8233d2d448c7a06e576613715180/medium",
  },
  {
    name: "Waffle with Carolina Style Smothered Chicken",
    description: "",
    price: 24,
    category: "Waffle Selections",
    tags: ["chicken", "sweet"],
    slug: "waffle-with-carolina-style-smothered-chicken",
  },
  {
    name: "Waffle with Chicken Wings",
    description: "",
    price: 24,
    priceNote: "$24/4 pcs",
    category: "Waffle Selections",
    tags: ["chicken", "sweet"],
    slug: "waffle-with-chicken-wings",
  },
  {
    name: "Sylvia\u2019s World-Famous Bar-B-Que Pork Ribs & Fried or Smothered Chicken",
    description: "With Sylvia\u2019s original sassy sauce.",
    price: 35,
    category: "Combinations",
    tags: ["chicken", "pork", "fried", "grilled"],
    slug: "sylvias-world-famous-bar-b-que-pork-ribs-fried-or-smothered-chicken",
    image: "https://static.spotapps.co/spots/c5/8fe157c043487fb463db6362f41d3e/medium",
  },
  {
    name: "Traditional Collard Greens (GF)",
    description: "Premium Side",
    price: 11,
    category: "Side Orders",
    tags: ["vegetarian"],
    slug: "traditional-collard-greens",
    image: "https://static.spotapps.co/spots/35/cf48dfa2214513807745562fea9e44/medium",
  },
  {
    name: "Vegetarian Collard Greens (V, GF)",
    description: "Premium Side",
    price: 11,
    category: "Side Orders",
    tags: ["vegetarian"],
    slug: "vegetarian-collard-greens",
    image: "https://static.spotapps.co/spots/e4/8626f350ed4db8ab198f57ad25062f/medium",
  },
  {
    name: "Baked Macaroni & Cheese (V)",
    description: "Premium Side",
    price: 11,
    category: "Side Orders",
    tags: ["vegetarian", "grilled"],
    slug: "baked-macaroni-cheese",
    image: "https://static.spotapps.co/spots/6b/1447b4d4af47b6b828978ba1ecdbd8/medium",
  },
  {
    name: "Candied Yams (V, GF)",
    description: "",
    price: 8,
    category: "Side Orders",
    tags: ["vegetarian"],
    slug: "candied-yams",
  },
  {
    name: "Potato Salad (V, GF)",
    description: "",
    price: 8,
    category: "Side Orders",
    tags: ["vegetarian"],
    slug: "potato-salad",
    image: "https://static.spotapps.co/spots/79/7a879d53b147fa8bc6c52ab5e9b2ea/medium",
  },
  {
    name: "Steamed Rice",
    description: "With brown gravy.",
    price: 7,
    category: "Side Orders",
    tags: [],
    slug: "steamed-rice",
    image: "https://static.spotapps.co/spots/f5/c29ab07a304d50a3a2272909eb8030/medium",
  },
  {
    name: "Grits (V)",
    description: "",
    price: 7,
    category: "Side Orders",
    tags: ["vegetarian"],
    slug: "grits",
    image: "https://static.spotapps.co/spots/65/6a8d623eae4368ad55c961f873e3e7/medium",
  },
  {
    name: "String Beans (V, GF)",
    description: "",
    price: 8,
    category: "Side Orders",
    tags: ["vegetarian"],
    slug: "string-beans",
    image: "https://static.spotapps.co/spots/44/fe6982ad564260a64c58d43e0a7414/medium",
  },
  {
    name: "Pickled Beets (V, GF)",
    description: "",
    price: 8,
    category: "Side Orders",
    tags: ["vegetarian"],
    slug: "pickled-beets",
    image: "https://static.spotapps.co/spots/84/f0dc708fe340a4ad497ff40453914d/medium",
  },
  {
    name: "Black Eyed Peas (GF)",
    description: "",
    price: 9,
    category: "Side Orders",
    tags: [],
    slug: "black-eyed-peas",
    image: "https://static.spotapps.co/spots/84/d1a5efce994d01ab23fdefbcfe4975/medium",
  },
  {
    name: "Sassy Rice (V, GF)",
    description: "Fri/Sat/Sun",
    price: 8,
    category: "Side Orders",
    tags: ["vegetarian"],
    slug: "sassy-rice",
  },
  {
    name: "Cornbread",
    description: "",
    price: 3,
    category: "Side Orders",
    tags: [],
    slug: "cornbread",
    image: "https://static.spotapps.co/spots/d0/5d16c339ff48a190ca9da4d59525fa/medium",
  },
  {
    name: "Sylvia\u2019s Sassy BBQ Sauce (GF, V)",
    description: "",
    price: 3,
    category: "Side Orders",
    tags: ["grilled"],
    slug: "sylvias-sassy-bbq-sauce",
    image: "https://static.spotapps.co/spots/17/ab38dd982b4b88b59617000fb57437/medium",
  },
  {
    name: "Sylvia\u2019s Brown Gravy (V)",
    description: "",
    price: 3,
    category: "Side Orders",
    tags: ["vegetarian"],
    slug: "sylvias-brown-gravy",
    image: "https://static.spotapps.co/spots/2a/27c41a275748678dc3ea90ee6636d3/medium",
  },
  {
    name: "Coconut Pineapple Cake",
    description: "",
    price: 10,
    category: "Dessert",
    tags: ["sweet"],
    slug: "coconut-pineapple-cake",
  },
  {
    name: "Red Velvet Cake",
    description: "",
    price: 10,
    category: "Dessert",
    tags: ["sweet"],
    slug: "red-velvet-cake",
    image: "https://static.spotapps.co/spots/1a/d9aac39a7141bf8d323a94b535cc5c/medium",
  },
  {
    name: "Chocolate Layer Cake",
    description: "Vanilla cake with chocolate frosting.",
    price: 10,
    category: "Dessert",
    tags: ["sweet"],
    slug: "chocolate-layer-cake",
    image: "https://static.spotapps.co/spots/6d/3cdf0121ae4c4585b8cb2e28de7c87/medium",
  },
  {
    name: "Sweet Potato Pie",
    description: "",
    price: 12,
    category: "Dessert",
    tags: ["sweet"],
    slug: "sweet-potato-pie",
    image: "https://static.spotapps.co/spots/55/57c8239b854d8ab9f7ede63f137d67/medium",
  },
  {
    name: "Peach Cobbler",
    description: "",
    price: 12,
    category: "Dessert",
    tags: ["sweet"],
    slug: "peach-cobbler",
    image: "https://static.spotapps.co/spots/66/290d80ad8c47b2a3a2fa3cb6fbe9f4/medium",
  },
  {
    name: "Peach Cobbler Waffle",
    description: "",
    price: 12,
    category: "Dessert",
    tags: ["sweet"],
    slug: "peach-cobbler-waffle",
  },
  {
    name: "Banana Pudding",
    description: "",
    price: 12,
    category: "Dessert",
    tags: ["sweet"],
    slug: "banana-pudding",
  },
  {
    name: "Vanilla Ice Cream",
    description: "",
    price: 7,
    category: "Dessert",
    tags: ["sweet"],
    slug: "vanilla-ice-cream",
  },
  {
    name: "A La Mode",
    description: "Add ice cream to any dessert",
    price: 4,
    priceNote: "$4.50",
    category: "Dessert",
    tags: ["sweet"],
    slug: "a-la-mode",
  }
];
